// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc1849.BobakTestRobot2.subsystems;
import org.usfirst.frc1849.BobakTestRobot2.RobotMap;
import org.usfirst.frc1849.BobakTestRobot2.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc1849.BobakTestRobot2.Robot;
/**
 *
 */
public class beltSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Relay belt_motor_1 = RobotMap.beltSystembelt_motor_1;
    Relay belt_motor_2 = RobotMap.beltSystembelt_motor_2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        System.out.println("Suck Ball - Default Command Entered");
    }
    
    public void forward() {
       // belt_motor_1.set(Relay.Value.kForward);
       // belt_motor_2.set(Relay.Value.kForward);
        System.out.println("Suck Ball - Forward Method");
        Robot.gatheringArmSystem.gatheringArmMotor_1.set(1);
        
        
    }
    
    public void reverse() {
        belt_motor_1.set(Relay.Value.kReverse);
        belt_motor_2.set(Relay.Value.kReverse);
    }
    
    public void stop() {
        belt_motor_1.set(Relay.Value.kOff);
        belt_motor_2.set(Relay.Value.kOff);
    }
    
    public void test() {
        System.out.println("BUTTON PRESSED");
    }
    
    
}
