// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc1849.BobakTestRobot2.subsystems;
import org.usfirst.frc1849.BobakTestRobot2.RobotMap;
import org.usfirst.frc1849.BobakTestRobot2.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class gatheringArmSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController gatheringArmMotor_1 = RobotMap.gatheringArmSystemgatheringArmMotor_1;
    SpeedController gatheringArmMotor_2 = RobotMap.gatheringArmSystemgatheringArmMotor_2;
    DigitalInput armRightDown_KillSwitch = RobotMap.gatheringArmSystemarmRightDown_KillSwitch;
    DigitalInput armRightUp_KillSwitch = RobotMap.gatheringArmSystemarmRightUp_KillSwitch;
    DigitalInput armLeftDown_KillSwitch = RobotMap.gatheringArmSystemarmLeftDown_KillSwitch;
    DigitalInput armLeftUp_KillSwitch = RobotMap.gatheringArmSystemarmLeftUp_KillSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
