// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc1849.BobakCommandRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay conveyorMotorLeft;
    public static Relay conveyorMotorRight;
    public static Talon  driveMotorLeft;
    public static Talon  driveMotorRight;
    public static Talon  throwingMotorLeft;
    public static Talon  throwingMotorRight;
    public static Jaguar armMotorLeft;
    public static Jaguar armMotorRight;
    
    public static DigitalInput armLeftDown_KillSwitch;  //Gathering Arms
    public static DigitalInput armRightDown_KillSwitch;
    public static DigitalInput armLeftUp_KillSwitch;
    public static DigitalInput armRightUp_KillSwitch;
    public static DigitalInput armThrow_KillSwitch; //Throwing Arm
    
    public static AnalogChannel sonar;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        conveyorMotorLeft = new Relay(1);
        conveyorMotorRight = new Relay(2);
        driveMotorLeft = new Talon(1);     /* drive motor 1 */
        driveMotorRight = new Talon(2);     /* drive motor 2 */
        throwingMotorLeft = new Talon(3); //Ball throwing motors
        throwingMotorRight = new Talon(4);
        armMotorRight = new Jaguar(5); //Moves gather arms up and down
        armMotorLeft = new Jaguar(6);
        
        armRightDown_KillSwitch = new DigitalInput(1);
        armRightUp_KillSwitch = new DigitalInput(2);
        armLeftDown_KillSwitch = new DigitalInput(3);
        armLeftUp_KillSwitch = new DigitalInput(4);
        armThrow_KillSwitch = new DigitalInput(5);

        sonar = new AnalogChannel(1);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
